### ISSUE TITLE
[Bug]: Failed to download from repository

### ISSUE THREAD

**Issue by codefendant** [firstof9/ha-renogy#21]
### The problem

Got status code 404 when trying to download https://github.com/firstof9/ha-renogy/releases/download/9fc8531/renogy.zip

![Screenshot_17-12-2024_201730_192 168 0 22](https://github.com/user-attachments/assets/c1ff9276-47ea-4e46-a75e-f8a1857ea220)

### What version of Home Assistant?

2024.12.4

### What version of Renogy?

N/A

### Anything in the logs that might be useful for us?

```txt
This error originated from a custom integration.

Logger: custom_components.hacs
Source: custom_components/hacs/base.py:709
integration: HACS (documentation, issues)
First occurred: 7:55:38 PM (2 occurrences)
Last logged: 7:56:44 PM

Download failed - Got status code 404 when trying to download https://github.com/firstof9/ha-renogy/releases/download/9fc8531/renogy.zip
Traceback (most recent call last):
File "/config/custom_components/hacs/base.py", line 709, in async_download_file
raise HacsException(
...<2 lines>...
)
custom_components.hacs.exceptions.HacsException: Got status code 404 when trying to download https://github.com/firstof9/ha-renogy/releases/download/9fc8531/renogy.zip
```

**Comment by Anto79-ops** [comment]
b10 is the latest.

Ignore that notification to update, that will go away on the first official release.

**Comment by firstof9** [comment]
What Anto79-ops said. :smiley:
