### ISSUE TITLE
[Bug]: One or both the keys are invalid. Please try again.

### ISSUE THREAD

**Issue by codefendant** [firstof9/ha-renogy#22]
### The problem

Getting error message "One or both the keys are invalid. Please try again."
 
![Screenshot_17-12-2024_21426_192 168 0 22](https://github.com/user-attachments/assets/620b4e39-9b89-4a02-9331-6eb4455eba4a)

I assume the Secret Key is the API Key and the Access Key is the API Key Name.

I generated one set of keys, and it didn't work.
Then I generated a second set of keys, and it still didn't work.
Swapped them around, still didn't work.

![Screenshot_17-12-2024_21245_platform renogy com](https://github.com/user-attachments/assets/79cc54aa-09b9-43c3-b2a6-0b224e4c8d56)

### What version of Home Assistant?

2024.12.4

### What version of Renogy?

N/A

### Anything in the logs that might be useful for us?

This error originated from a custom integration.

Logger: custom_components.renogy.config_flow
Source: custom_components/renogy/config_flow.py:45
integration: renogy (documentation, issues)
First occurred: 8:54:51 PM (7 occurrences)
Last logged: 9:19:20 PM

Invalid key(s).
Traceback (most recent call last):
  File "/config/custom_components/renogy/config_flow.py", line 45, in async_step_user
    await renogy.get_devices()
  File "/usr/local/lib/python3.13/site-packages/renogyapi/__init__.py", line 115, in get_devices
    response = await self.process_request(url, headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/renogyapi/__init__.py", line 81, in process_request
    raise NotAuthorized
renogyapi.exceptions.NotAuthorized

**Comment by Anto79-ops** [comment]
Hi,

When you go to create a new key on the Renogy API platform, it first shows you the secret key or `sk` key. Copy paste this because it only shows it once. Then, when you press ok, it shows you the second key or the access key or `ak` key.

You can always go back and see the `ak` key but not the `sk` key. If you lose or forget the `sk` key, just delete it and make a new one.

**Comment by firstof9** [comment]
> When you go to create a new key on the Renogy API platform, it first shows you the secret key or `sk` key. Copy paste this because it only shows it once. Then, when you press ok, it shows you the second key or the access key or `ak` key.

Feel free to whip up the steps to make the keys, we can add it to the README

**Comment by Anto79-ops** [comment]
please see here:
https://github.com/firstof9/ha-renogy/pull/24
