### ISSUE TITLE
[Bug]: Error contacting Renogy API: list index out of range

### ISSUE THREAD

**Issue by danc89** [firstof9/ha-renogy#29]
### The problem

Unable to load after inputting keys

### What version of Home Assistant?

core-2024.12.5

### What version of Renogy?

1.0.0-b7

### Anything in the logs that might be useful for us?

```txt
Error contacting Renogy API: list index out of range
Traceback (most recent call last):
  File "/config/custom_components/renogy/config_flow.py", line 45, in async_step_user
    await renogy.get_devices()
  File "/usr/local/lib/python3.13/site-packages/renogyapi/__init__.py", line 119, in get_devices
    if "deviceId" in response[0].keys():
                     ~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by firstof9** [comment]
Use the latest beta. b9

**Comment by danc89** [comment]
I have tried all the versions, all still the same

**Comment by Anto79-ops** [comment]
I think @firstof9 fixed this [here](https://github.com/firstof9/py-renogy/pull/4) but no update was issued.

**Comment by Anto79-ops** [comment]
https://github.com/firstof9/py-renogy/issues/3

**Comment by firstof9** [comment]
Odd, it should have been in b9, try b11.

**Comment by danc89** [comment]
Thanks for the help guys, its now saying "The API returned no devices for your account."
I'm not sure if i'm missing something. My DC home app will show me my batteries and and I think my M1 panel.

**Comment by Anto79-ops** [comment]
yeah, make sure your M1 panel is paired with the devices. I know you can bypass the M1/ONE Core by adding devices directly to the app, but its only the M1/ONE Core hub that communucates with the API. When you go the the M1, do you see devices reporting to it and the email its connected to, is that the same email you used for the API keys account?

**Comment by danc89** [comment]
Captain stupid here, m1 panel had un paired itself, all sorted now guys. Just waiting for it to actually connect to my batteries.
Thanks guys !

**Comment by firstof9** [comment]
Someone previously had a similar issue so I wouldn't put yourself down by any means :slightly_smiling_face: 
Enjoy!
